spring.application.name=melody-backend

server.port=8080

# =====================================================
# SQL SERVER
# =====================================================

spring.datasource.url=jdbc:sqlserver://DESKTOP-9KABSEA\\SQLEXPRESS;databaseName=MelodyDB;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Windows Authentication
spring.datasource.username=
spring.datasource.password=

# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# =====================================================
# JWT
# =====================================================

melody.jwt.secret=MelodySuperSecretKeyForJwtAuthentication2026VeryLongSecretKey
melody.jwt.expiration=86400000

# =====================================================
# SQL INITIALIZATION
# =====================================================

spring.sql.init.mode=never